# Generated by Django 4.0.4 on 2022-06-22 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activated_Question_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('time_to_send', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.BigAutoField(db_column='answer_id', primary_key=True, serialize=False)),
                ('ans', models.TextField(default='')),
                ('isCorrect', models.BooleanField(default=False)),
                ('explanation', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(db_column='question_id', primary_key=True, serialize=False)),
                ('ques', models.TextField(default='')),
                ('order', models.IntegerField(default=0)),
                ('time_Limit', models.IntegerField(default=60, help_text='duration of the question in minutes')),
                ('openDT', models.DateTimeField(default=datetime.datetime.now)),
                ('closeDT', models.DateTimeField(default=datetime.datetime.now)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer')),
                ('ques', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('std', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('question_bank_id', models.BigAutoField(db_column='question_bank_id', primary_key=True, serialize=False)),
                ('topic', models.CharField(default='Topic', max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('number_of_attempts', models.IntegerField(default=3)),
                ('isRandom', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('BIDIURNAL', 'Every other day'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=120)),
                ('assigned_students', models.ManyToManyField(through='questions.Activated_Question_Bank', to='main.student')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name_plural': 'Question_Banks',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question_bank'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='activated_question_bank',
            name='question_bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question_bank'),
        ),
        migrations.AddField(
            model_name='activated_question_bank',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
