# Generated by Django 4.0.5 on 2022-07-21 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.BigAutoField(db_column='answer_id', primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(db_column='question_id', primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('order', models.IntegerField(default=0)),
                ('open_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(db_column='section_id', primary_key=True, serialize=False)),
                ('topic', models.CharField(default='Topic', max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('BIDIURNAL', 'Every other day'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.section')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='assigned_students',
            field=models.ManyToManyField(through='questions.SectionScore', to='main.student'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
