# Generated by Django 4.0.5 on 2022-07-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='assigned_students',
        ),
        migrations.DeleteModel(
            name='SectionScore',
        ),
    ]
