# Generated by Django 4.0.4 on 2022-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.BigAutoField(db_column='answer_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.BigAutoField(db_column='question_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='question_bank_id',
            field=models.BigAutoField(db_column='question_bank_id', primary_key=True, serialize=False),
        ),
    ]
