# Generated by Django 4.0.4 on 2022-06-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_answer_id_alter_question_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activated_question_bank',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
