# Generated by Django 4.0.4 on 2022-06-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activated_Question_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('time_to_send', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.BigAutoField(db_column='answer_id', default=0, primary_key=True, serialize=False)),
                ('ans', models.TextField(default='')),
                ('isCorrect', models.BooleanField(default=False)),
                ('explanation', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(db_column='course_id', default=0, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(db_column='question_id', default=0, primary_key=True, serialize=False)),
                ('ques', models.TextField(default='')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=255, unique=True)),
                ('student_id', models.CharField(default='', max_length=255)),
                ('instructor_id', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('ques', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('std', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('question_bank_id', models.BigAutoField(db_column='question_bank_id', default=0, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='Topic', max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('number_of_attempts', models.IntegerField(default=3)),
                ('isRandom', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('BIDIURNAL', 'Every other day'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=120)),
                ('assigned_students', models.ManyToManyField(through='main.Activated_Question_Bank', to='main.student')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question_bank'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructors+', to='main.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students+', to='main.student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AddField(
            model_name='activated_question_bank',
            name='question_bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question_bank'),
        ),
        migrations.AddField(
            model_name='activated_question_bank',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
