# Generated by Django 4.0.4 on 2022-06-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='question_bank',
            name='assigned_students',
        ),
        migrations.RemoveField(
            model_name='question_bank',
            name='course',
        ),
        migrations.RemoveField(
            model_name='response',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='response',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='response',
            name='std',
        ),
        migrations.DeleteModel(
            name='Activated_Question_Bank',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Question_Bank',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
