# Generated by Django 4.0.4 on 2022-05-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='ques',
        ),
    ]
