# Generated by Django 4.0.5 on 2022-07-03 22:05

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220703_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], default='FALL', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), main.models.max_value_current_year]),
        ),
    ]
