# Generated by Django 4.0.4 on 2022-05-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_answer_ans_rename_name_question_ques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ques',
            new_name='name',
        ),
    ]
