# Generated by Django 4.0.4 on 2022-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_answer_question_remove_question_question_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.BigAutoField(db_column='course_id', primary_key=True, serialize=False),
        ),
    ]
