# Generated by Django 4.0.5 on 2022-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_access_code_course_semester_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], default='SUMMER', max_length=120),
        ),
    ]
