# Generated by Django 4.0.4 on 2022-05-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='isCorrect',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='ques',
        ),
    ]
