# Generated by Django 4.0.4 on 2022-05-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_correct_answer_iscorrect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='ans',
        ),
    ]
