# Generated by Django 4.0.4 on 2022-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instructor_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
